services:
  - type: web
    name: portfolio-website
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false

